spring:
  profiles:
    active: default

---

spring:
  profiles: default
  application:
    name: registry
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---

spring:
  profiles: eureka1
  application:
    name: registry
server:
  port: 8761
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      zone: zone1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://localhost:8761/eureka
      zone2: http://localhost:8762/eureka
    region: region1
    availability-zones:
      region1: zone1,zone2
  server:
    wait-time-in-ms-when-sync-empty: 0

---

spring:
  profiles: eureka2
  application:
    name: registry
server:
  port: 8762
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://localhost:8761/eureka
      zone2: http://localhost:8762/eureka
    region: region1
    availability-zones:
      region1: zone1,zone2
  server:
    wait-time-in-ms-when-sync-empty: 0